
import React, { Component } from 'react';

class MinistriesPanel extends Component {
    render() {
        return (
          <section className="elementor-section elementor-top-section elementor-element elementor-element-30d8013 elementor-section-boxed elementor-section-height-default elementor-section-height-default sc_fly_static trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="30d8013" data-element_type="section" id="our-ministry">
          <div className="elementor-background-overlay" />
          <div className="elementor-container elementor-column-gap-extended">
            <div className="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-483ab07 sc_layouts_column_align_center sc_layouts_column sc_inner_width_none sc_content_align_inherit sc_layouts_column_icons_position_left sc_fly_static trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="483ab07" data-element_type="column">
              <div className="elementor-widget-wrap elementor-element-populated">
                <div className="elementor-element elementor-element-e2c9233 sc_height_huge sc_fly_static elementor-widget elementor-widget-spacer trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="e2c9233" data-element_type="widget" data-widget_type="spacer.default">
                  <div className="elementor-widget-container">
                    <div className="elementor-spacer">
                      <div className="elementor-spacer-inner" />
                    </div>
                  </div>
                </div>
                <div className="elementor-element elementor-element-90150c7 sc_fly_static elementor-widget elementor-widget-trx_sc_title trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="90150c7" data-element_type="widget" data-widget_type="trx_sc_title.default">
                  <div className="elementor-widget-container">
                    <div className="sc_title sc_title_default"><h2 className="sc_item_title sc_title_title sc_align_center sc_item_title_style_default"><span className="sc_item_title_text">Our Ministries</span></h2></div>		</div>
                </div>
                <div className="elementor-element elementor-element-f380110 sc_fly_static elementor-widget elementor-widget-spacer trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="f380110" data-element_type="widget" data-widget_type="spacer.default">
                  <div className="elementor-widget-container">
                    <div className="elementor-spacer">
                      <div className="elementor-spacer-inner" />
                    </div>
                  </div>
                </div>
                <div className="elementor-element elementor-element-aeb8839 sc_style_default sc_fly_static elementor-widget elementor-widget-trx_sc_blogger trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="aeb8839" data-element_type="widget" data-widget_type="trx_sc_blogger.default">
                  <div className="elementor-widget-container">
                    <div className="sc_blogger sc_blogger_default sc_blogger_default_over_bottom sc_item_filters_tabs_none alignnone"><div className="sc_blogger_slider sc_item_slider slider_swiper_outer slider_outer slider_outer_nocontrols slider_outer_pagination slider_outer_pagination_bullets slider_outer_pagination_pos_bottom slider_outer_nocentered slider_outer_overflow_hidden slider_outer_multi" id="swiper_09617749833046261_outer">
                        <div data-slides-per-view-breakpoints="{&quot;999999&quot;:3}" className="slider_container swiper-slider-container slider_swiper slider_noresize slider_nocontrols slider_pagination slider_pagination_bullets slider_pagination_pos_bottom slider_nocentered slider_overflow_hidden slider_multi swiper_09617749833046261 inited swiper-container-initialized swiper-container-horizontal" data-slides-per-view={3} data-slides-space={30} data-effect="slide" data-slides-min-width={220} data-pagination="bullets" data-direction="horizontal" data-mouse-wheel={0} data-autoplay={1} data-loop={1} data-free-mode={0} data-slides-centered={0} data-slides-overflow={0} id="swiper_09617749833046261" style={{display: 'block', opacity: 1, cursor: 'grab'}} data-busy={0}>
                          <div className="slides slider-wrapper swiper-wrapper sc_item_columns_3" style={{transitionDuration: '0ms', transform: 'translate3d(-2260px, 0px, 0px)'}}><div className="slider-slide swiper-slide swiper-slide-duplicate" data-slide-number={6} data-swiper-slide-index={6} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25639} data-item-number={7} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_odd sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25639 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_1597860070" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={7}><a href="https://marianretreatcentre.org/services/ministry-of-spiritual-sharing/" rel="bookmark">Ministry of Spiritual Sharing</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/ministry-of-spiritual-sharing/" />			<a href="https://marianretreatcentre.org/services/ministry-of-spiritual-sharing/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide swiper-slide-duplicate" data-slide-number={7} data-swiper-slide-index={7} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25654} data-item-number={8} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_even sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25654 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_1489315634" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={8}><a href="https://marianretreatcentre.org/services/missionaries-of-grace/" rel="bookmark">Missionaries of Grace</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/missionaries-of-grace/" />			<a href="https://marianretreatcentre.org/services/missionaries-of-grace/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide swiper-slide-duplicate" data-slide-number={8} data-swiper-slide-index={8} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25663} data-item-number={9} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_odd sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25663 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_1868091582" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={9}><a href="https://marianretreatcentre.org/services/daughters-of-divine-grace/" rel="bookmark">Daughters of Divine Grace</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/daughters-of-divine-grace/" />			<a href="https://marianretreatcentre.org/services/daughters-of-divine-grace/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide" data-slide-number={0} data-swiper-slide-index={0} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25573} data-item-number={1} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_odd sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25573 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_1284598201" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={1}><a href="https://marianretreatcentre.org/services/healing-deliverance-residential-retreat/" rel="bookmark">Healing &amp; Deliverance Residential Retreat</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/healing-deliverance-residential-retreat/" />			<a href="https://marianretreatcentre.org/services/healing-deliverance-residential-retreat/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide" data-slide-number={1} data-swiper-slide-index={1} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25607} data-item-number={2} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_even sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25607 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_436026443" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={2}><a href="https://marianretreatcentre.org/services/grace-anointing-bible-convention/" rel="bookmark">Grace Anointing Bible Convention</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/grace-anointing-bible-convention/" />			<a href="https://marianretreatcentre.org/services/grace-anointing-bible-convention/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide swiper-slide-prev" data-slide-number={2} data-swiper-slide-index={2} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25613} data-item-number={3} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_odd sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25613 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_842452614" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={3}><a href="https://marianretreatcentre.org/services/first-saturday-bible-convention/" rel="bookmark">First Saturday Bible Convention</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/first-saturday-bible-convention/" />			<a href="https://marianretreatcentre.org/services/first-saturday-bible-convention/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide swiper-slide-active" data-slide-number={3} data-swiper-slide-index={3} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25619} data-item-number={4} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_even sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25619 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_1238116010" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={4}><a href="https://marianretreatcentre.org/services/krupabalyam-ministry-of-chidren/" rel="bookmark">Krupabalyam – Ministry of Chidren</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/krupabalyam-ministry-of-chidren/" />			<a href="https://marianretreatcentre.org/services/krupabalyam-ministry-of-chidren/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide swiper-slide-next" data-slide-number={4} data-swiper-slide-index={4} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25626} data-item-number={5} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_odd sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25626 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_369013568" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={5}><a href="https://marianretreatcentre.org/services/ministry-of-intercession/" rel="bookmark">Ministry of Intercession</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/ministry-of-intercession/" />			<a href="https://marianretreatcentre.org/services/ministry-of-intercession/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide" data-slide-number={5} data-swiper-slide-index={5} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25633} data-item-number={6} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_even sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25633 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_965729653" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={6}><a href="https://marianretreatcentre.org/services/sacrament-of-reconciliation/" rel="bookmark">Sacrament of Reconciliation</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/sacrament-of-reconciliation/" />			<a href="https://marianretreatcentre.org/services/sacrament-of-reconciliation/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide" data-slide-number={6} data-swiper-slide-index={6} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25639} data-item-number={7} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_odd sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25639 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_1597860070" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={7}><a href="https://marianretreatcentre.org/services/ministry-of-spiritual-sharing/" rel="bookmark">Ministry of Spiritual Sharing</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/ministry-of-spiritual-sharing/" />			<a href="https://marianretreatcentre.org/services/ministry-of-spiritual-sharing/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide" data-slide-number={7} data-swiper-slide-index={7} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25654} data-item-number={8} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_even sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25654 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_1489315634" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={8}><a href="https://marianretreatcentre.org/services/missionaries-of-grace/" rel="bookmark">Missionaries of Grace</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/missionaries-of-grace/" />			<a href="https://marianretreatcentre.org/services/missionaries-of-grace/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide" data-slide-number={8} data-swiper-slide-index={8} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25663} data-item-number={9} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_odd sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25663 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_1868091582" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={9}><a href="https://marianretreatcentre.org/services/daughters-of-divine-grace/" rel="bookmark">Daughters of Divine Grace</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/daughters-of-divine-grace/" />			<a href="https://marianretreatcentre.org/services/daughters-of-divine-grace/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide swiper-slide-duplicate" data-slide-number={0} data-swiper-slide-index={0} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25573} data-item-number={1} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_odd sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25573 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_1284598201" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={1}><a href="https://marianretreatcentre.org/services/healing-deliverance-residential-retreat/" rel="bookmark">Healing &amp; Deliverance Residential Retreat</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/healing-deliverance-residential-retreat/" />			<a href="https://marianretreatcentre.org/services/healing-deliverance-residential-retreat/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide swiper-slide-duplicate" data-slide-number={1} data-swiper-slide-index={1} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25607} data-item-number={2} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_even sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25607 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_436026443" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={2}><a href="https://marianretreatcentre.org/services/grace-anointing-bible-convention/" rel="bookmark">Grace Anointing Bible Convention</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/grace-anointing-bible-convention/" />			<a href="https://marianretreatcentre.org/services/grace-anointing-bible-convention/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div><div className="slider-slide swiper-slide swiper-slide-duplicate swiper-slide-duplicate-prev" data-slide-number={2} data-swiper-slide-index={2} style={{width: '346.667px', marginRight: '30px'}}><div data-post-id={25613} data-item-number={3} className="sc_blogger_item sc_item_container post_container sc_blogger_item_default sc_blogger_item_default_over_bottom sc_blogger_item_odd sc_blogger_item_align_none post_format_standard sc_blogger_item_with_image sc_blogger_item_no_excerpt sc_blogger_item_on_plate sc_blogger_item_image_position_top post-25613 cpt_services type-cpt_services status-publish has-post-thumbnail hentry cpt_services_group-general"><div className="sc_blogger_item_body"><div className="post_featured with_thumb hover_link sc_item_featured sc_blogger_item_featured post_featured_bg" data-ratio="1:1"><span className="post_thumb post_thumb_bg bg_in athos_inline_842452614" />						<div className="mask" />
                                    <div className="post_info_bc"><h5 className="sc_blogger_item_title entry-title" data-item-number={3}><a href="https://marianretreatcentre.org/services/first-saturday-bible-convention/" rel="bookmark">First Saturday Bible Convention</a></h5></div><a className="post_link sc_blogger_item_link" href="https://marianretreatcentre.org/services/first-saturday-bible-convention/" />			<a href="https://marianretreatcentre.org/services/first-saturday-bible-convention/" aria-hidden="true" className="link" />
                                  </div></div>{/* .sc_blogger_item_body */}</div>{/* .sc_blogger_item */}</div></div><span className="swiper-notification" aria-live="assertive" aria-atomic="true" /></div><div className="slider_pagination_wrap swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"><span className="swiper-pagination-bullet" tabIndex={0} role="button" aria-label="Go to slide 1" /><span className="swiper-pagination-bullet" tabIndex={0} role="button" aria-label="Go to slide 2" /><span className="swiper-pagination-bullet" tabIndex={0} role="button" aria-label="Go to slide 3" /><span className="swiper-pagination-bullet swiper-pagination-bullet-active" tabIndex={0} role="button" aria-label="Go to slide 4" /><span className="swiper-pagination-bullet" tabIndex={0} role="button" aria-label="Go to slide 5" /><span className="swiper-pagination-bullet" tabIndex={0} role="button" aria-label="Go to slide 6" /><span className="swiper-pagination-bullet" tabIndex={0} role="button" aria-label="Go to slide 7" /><span className="swiper-pagination-bullet" tabIndex={0} role="button" aria-label="Go to slide 8" /><span className="swiper-pagination-bullet" tabIndex={0} role="button" aria-label="Go to slide 9" /></div></div></div>		</div>
                </div>
                <div className="elementor-element elementor-element-dbe52a1 sc_height_huge sc_fly_static elementor-widget elementor-widget-spacer trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited" data-id="dbe52a1" data-element_type="widget" data-widget_type="spacer.default">
                  <div className="elementor-widget-container">
                    <div className="elementor-spacer">
                      <div className="elementor-spacer-inner" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        );
    }
}

export default MinistriesPanel;
